#!/usr/bin/python

# Written by Abhishek Bagusetty to apply Atactic Condition
# to the polymer structure generated by moltemplae program
# especially for Poly(Vinyl Alchohol) polymer.
#
# Date : 2016, March 16
# Johnson Group, University of Pittsburgh

import random
import os
import sys

os.system("vmd -dispdev text -e ./rewrite-datalammps-topotools.tcl")

